language: android
jdk: oraclejdk7
before_install:
 - chmod +x gradlew
 - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force > /dev/null

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - android-23

script: ./gradlew assembleDebug
