language: android
jdk: oraclejdk7
before_install:
 - chmod +x gradlew
 - echo yes | android update sdk --all --filter build-tools-21.1.1 --no-ui --force > /dev/null

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.1

script: ./gradlew assembleDebug
